### ISSUE TITLE
vim fails disassembly

### ISSUE THREAD

**Issue by jrmuizel** [GrammaTech/ddisasm#21]
vim compiled with gcc-7.5.0 fails with:

```
Printing assembler ddisasm: /root/gtirb-pprinter/src/gtirb_pprinter/ElfPrettyPrinter.cpp:195: void gtirb_pprint::ElfPrettyPrinter::printSymbolHeader(std::ostream&, const gtirb::Symbol&, bool): Assertion `!"unknown visibility in elfSymbolInfo!"' failed.
```

This is with ddisasm 1.4 (1cbb62cb91f4a51b615e0150ebb25fc97dcef640)

I've attached the binary
[vim.zip](https://github.com/GrammaTech/ddisasm/files/6086126/vim.zip)

I ran into this while trying out ddisasm on https://github.com/pangine/disasm-benchmark

**Comment by aeflores** [comment]
Hi @jrmuizel thanks for reporting! we will look into this and the other issues.
I would be curious to know the results of that evaluation overall if you have them available

**Comment by jrmuizel** [comment]
I don't have overall results. I filed https://github.com/pangine/disasm-benchmark/issues/1 and sounds like the authors tried to get results but there were too many failures.

**Comment by junghee** [comment]
We were able to reproduce the failure with the commit hash of ddisasm. I used an older version of gtirb-pprinter because the related commit hash was not reported.

We confirmed that vim builds OK with the latest versions of ddisasm + gtirb-pprinter. Here are the commit hashs:

ddisasm: 1cbb62cb91f4a51b615e0150ebb25fc97dcef640

gtirb-pprinter: 370eebc7ed61eaf0a721e0bd441d67e2c8024319

**Comment by jrmuizel** [comment]
I was using gtirb-pprinter: f6e382346171dc2e3a3ba16948f83cda13e1242c

**Comment by jrmuizel** [comment]
I see the same thing with 370eebc7ed61eaf0a721e0bd441d67e2c8024319. Maybe the problem is the version of LIEF? I'm using LIEF-0.10.1

**Comment by junghee** [comment]
I was using LIEF-0.10.0, but I don't really think it's a LIEF problem.
Did you remove your build directory and try a clean rebuild?

**Comment by jrmuizel** [comment]
I still see the problem with a clean no-cache build of this docker file: https://github.com/jrmuizel/disasm-eval-disasms/blob/main/dockerfiles/Dockerfile.ddisasm2

**Comment by junghee** [comment]
I'm not sure why I was not able to reproduce it earlier, but I tried the setup in your Dockerfile from scratch, and reproduced the failure. A fix has been merged to the gtirb-pprinter master.
Hope it works on your end as well.

**Comment by jrmuizel** [comment]
I can still reproduce this with a fresh rebuild of https://github.com/jrmuizel/disasm-eval-disasms/blob/main/dockerfiles/Dockerfile.ddisasm2 (which has been updated to use gtirb-pprinter a974d7a43a1b51c15793a6322c75c8065f8f4d8d)

**Comment by junghee** [comment]
That one seems older than my fix.
Sorry, I should have specified the hash number earlier.
The hash for the fix is 913269153e66fd133a80f92ef66ad4e2cf72ab54.

**Comment by jrmuizel** [comment]
That hash doesn't exist in the in the gtirb-pprinter repository: https://github.com/GrammaTech/gtirb-pprinter/commit/913269153e66fd133a80f92ef66ad4e2cf72ab54

**Comment by aeflores** [comment]
Oh, it looks like we have an issue with the updates to the public repo. I'll look into it!

**Comment by jrmuizel** [comment]
That fixed it. Thanks.
